/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Point;
import javax.swing.JOptionPane;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.Enumeration;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nelson
 */
public class PrincipalWindow extends javax.swing.JFrame {

    private String ipSelected;
    
    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        initComponents();
        init();
    }

    private void init() {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        JP_Start.setVisible(false);
        JP_Ipv4Available.setVisible(false);
    }

    public void getIpv4Available() {
        try {
            Enumeration nis = NetworkInterface.getNetworkInterfaces();
            //List<String> rowData = new ArrayList<>();
            String[] columns = {"Ip"};
            DefaultTableModel model = new DefaultTableModel(columns, 0);            
            
            while (nis.hasMoreElements()) {
                NetworkInterface ni = (NetworkInterface) nis.nextElement();
                Enumeration ias = ni.getInetAddresses();
                while (ias.hasMoreElements()) {
                    InetAddress ia = (InetAddress) ias.nextElement();                    
                    if (ia instanceof Inet4Address) {
                        Object[] newRow = {ia.getHostAddress()};
                        model.addRow(newRow);
                    }
                }
            }
            JTable_IP.setModel(model);
        } catch (SocketException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        JP_Start = new javax.swing.JPanel();
        JP_Ipv4Available = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_IP = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JP_Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jtf_login = new javax.swing.JTextField();
        JBtn_Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guerra del mar");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        JP_Start.setBackground(new java.awt.Color(255, 255, 255));
        JP_Start.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout JP_StartLayout = new javax.swing.GroupLayout(JP_Start);
        JP_Start.setLayout(JP_StartLayout);
        JP_StartLayout.setHorizontalGroup(
            JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        JP_StartLayout.setVerticalGroup(
            JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jDesktopPane1.add(JP_Start);
        JP_Start.setBounds(0, 0, 810, 590);

        JP_Ipv4Available.setBackground(new java.awt.Color(255, 255, 255));
        JP_Ipv4Available.setPreferredSize(new java.awt.Dimension(800, 600));
        JP_Ipv4Available.setLayout(null);

        JTable_IP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Ip"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_IP);

        JP_Ipv4Available.add(jScrollPane1);
        jScrollPane1.setBounds(174, 86, 452, 159);

        jButton1.setText("Seleccionar");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JP_Ipv4Available.add(jButton1);
        jButton1.setBounds(340, 300, 120, 25);

        jLabel2.setText("Seleccione la direcció IP del servidor");
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 20));
        JP_Ipv4Available.add(jLabel2);
        jLabel2.setBounds(275, 40, 250, 20);

        jDesktopPane1.add(JP_Ipv4Available);
        JP_Ipv4Available.setBounds(0, 0, 800, 600);

        JP_Login.setBackground(new java.awt.Color(255, 255, 255));
        JP_Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JP_Login.setName("JP_Login"); // NOI18N
        JP_Login.setPreferredSize(new java.awt.Dimension(400, 300));
        JP_Login.setLayout(null);

        jLabel1.setText("Ingrese su nombre de usuario");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 20));
        JP_Login.add(jLabel1);
        jLabel1.setBounds(100, 90, 200, 20);

        Jtf_login.setName(""); // NOI18N
        Jtf_login.setPreferredSize(new java.awt.Dimension(100, 25));
        Jtf_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_loginActionPerformed(evt);
            }
        });
        Jtf_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Jtf_loginKeyPressed(evt);
            }
        });
        JP_Login.add(Jtf_login);
        Jtf_login.setBounds(150, 140, 102, 25);

        JBtn_Login.setText("Ingresar");
        JBtn_Login.setPreferredSize(new java.awt.Dimension(100, 25));
        JBtn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_LoginActionPerformed(evt);
            }
        });
        JP_Login.add(JBtn_Login);
        JBtn_Login.setBounds(150, 200, 100, 25);

        jDesktopPane1.add(JP_Login);
        JP_Login.setBounds(200, 100, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_loginActionPerformed

    private void JBtn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_LoginActionPerformed
        validateLogin();
    }//GEN-LAST:event_JBtn_LoginActionPerformed

    private boolean validateLogin(){
        if (!Jtf_login.getText().isEmpty()) {
            //consultarle al servidor si es nombre único
            JP_Login.setVisible(false); 
            getIpv4Available();
            JP_Ipv4Available.setVisible(true);
            return true;
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de usuario");
            return false;
        }
    }
    
    private void Jtf_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_loginKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            validateLogin();
        }
    }//GEN-LAST:event_Jtf_loginKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(JTable_IP.getSelectedRow() != -1){
            ipSelected = JTable_IP.getModel().getValueAt(JTable_IP.getSelectedRow(), JTable_IP.getSelectedColumn()).toString();
            JP_Ipv4Available.setVisible(false);
            JP_Start.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione la dirección ip del servidor");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_Login;
    private javax.swing.JPanel JP_Ipv4Available;
    private javax.swing.JPanel JP_Login;
    private javax.swing.JPanel JP_Start;
    private javax.swing.JTable JTable_IP;
    private javax.swing.JTextField Jtf_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
