package view;

import controller.Client;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import util.IConstants;
import javax.swing.JOptionPane;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.util.Enumeration;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.Boton;
import static util.IConstants.IP_SERVER_LOCAL;
import static util.IConstants.SEND_MESSAGE;
import static util.IConstants.SERVER_PORT;
import static util.IConstants.UPDATE_CONVERSATION;

/**
 *
 * @author Nelson
 */
public class PrincipalWindow extends javax.swing.JFrame implements IConstants{

    private String ipSelected;
    private Client myClient;    
    private Timer timer;
    
    public static String userName;
    
    int fila = 15;
    int columna = 15;
    Boton [][] panelBotones = new Boton[fila][columna];
    
    public String getIpSelected() {
        return ipSelected;
    }

    public void setIpSelected(String ipSelected) {
        this.ipSelected = ipSelected;
    }
    
    /**
     * Creates new form PrincipalWindow
     */
    public PrincipalWindow() {
        initComponents();
        init();
    }

    private void init() {
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        JP_Start.setVisible(false);
        JP_Login.setVisible(false);    
        
        botones();
        
        jPanel1.setOpaque(false);
        
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                myClient = new Client(SERVER_PORT, IP_SERVER_LOCAL, UPDATE_CONVERSATION, null);
                myClient.start();

                String status = myClient.getStatus();
                while (status.equals("")) {
                    status = myClient.getStatus();
                }
                jTxtA_Conversation.setText(status);
            }
        });
        getIpv4Available();

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                myClient = new Client(SERVER_PORT, IP_SERVER_LOCAL, USER_OFF, userName);
                myClient.start();
            }
        });
    }

    public void getIpv4Available() {
        try {
            Enumeration nis = NetworkInterface.getNetworkInterfaces();
            //List<String> rowData = new ArrayList<>();
            String[] columns = {"Ip"};
            DefaultTableModel model = new DefaultTableModel(columns, 0);            
            
            while (nis.hasMoreElements()) {
                NetworkInterface ni = (NetworkInterface) nis.nextElement();
                Enumeration ias = ni.getInetAddresses();
                while (ias.hasMoreElements()) {
                    InetAddress ia = (InetAddress) ias.nextElement();                    
                    if (ia instanceof Inet4Address) {
                        Object[] newRow = {ia.getHostAddress()};
                        model.addRow(newRow);
                    }
                }
            }
            JTable_IP.setModel(model);
        } catch (SocketException ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        JP_Start = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_Users = new javax.swing.JTable();
        JBtn_invite = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtA_Conversation = new javax.swing.JTextArea();
        jTxtF_Message = new javax.swing.JTextField();
        JBtn_SendMessage = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JP_Ipv4Available = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_IP = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JP_Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jtf_login = new javax.swing.JTextField();
        JBtn_Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guerra del mar");
        setSize(new java.awt.Dimension(800, 600));

        JP_Start.setBackground(new java.awt.Color(255, 255, 255));
        JP_Start.setPreferredSize(new java.awt.Dimension(800, 600));

        JTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre de ususario"
            }
        ));
        jScrollPane2.setViewportView(JTable_Users);

        JBtn_invite.setText("Invitar");
        JBtn_invite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_inviteActionPerformed(evt);
            }
        });

        jTxtA_Conversation.setEditable(false);
        jTxtA_Conversation.setColumns(20);
        jTxtA_Conversation.setRows(5);
        jTxtA_Conversation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(jTxtA_Conversation);

        jTxtF_Message.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTxtF_Message.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtF_MessageKeyPressed(evt);
            }
        });

        JBtn_SendMessage.setText("Enviar");
        JBtn_SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_SendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        jButton2.setText("Fuente Energia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mercado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mina");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Armería");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Templo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Conector");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Insertar");

        javax.swing.GroupLayout JP_StartLayout = new javax.swing.GroupLayout(JP_Start);
        JP_Start.setLayout(JP_StartLayout);
        JP_StartLayout.setHorizontalGroup(
            JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_StartLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_StartLayout.createSequentialGroup()
                        .addComponent(jTxtF_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBtn_SendMessage)))
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(JBtn_invite)
                .addGap(76, 76, 76))
            .addGroup(JP_StartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_StartLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JP_StartLayout.setVerticalGroup(
            JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_StartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton7)
                        .addComponent(jButton8))
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtn_invite)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JP_StartLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JP_StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtn_SendMessage)
                            .addComponent(jTxtF_Message, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jDesktopPane1.add(JP_Start);
        JP_Start.setBounds(0, 0, 810, 590);

        JP_Ipv4Available.setBackground(new java.awt.Color(255, 255, 255));
        JP_Ipv4Available.setPreferredSize(new java.awt.Dimension(800, 600));
        JP_Ipv4Available.setLayout(null);

        JTable_IP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Ip"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTable_IP);

        JP_Ipv4Available.add(jScrollPane1);
        jScrollPane1.setBounds(174, 86, 452, 159);

        jButton1.setText("Seleccionar");
        jButton1.setPreferredSize(new java.awt.Dimension(120, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JP_Ipv4Available.add(jButton1);
        jButton1.setBounds(340, 300, 120, 25);

        jLabel2.setText("Seleccione la dirección IP del servidor");
        jLabel2.setPreferredSize(new java.awt.Dimension(250, 20));
        JP_Ipv4Available.add(jLabel2);
        jLabel2.setBounds(275, 40, 250, 20);

        jDesktopPane1.add(JP_Ipv4Available);
        JP_Ipv4Available.setBounds(0, 0, 800, 600);

        JP_Login.setBackground(new java.awt.Color(255, 255, 255));
        JP_Login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        JP_Login.setName("JP_Login"); // NOI18N
        JP_Login.setPreferredSize(new java.awt.Dimension(400, 300));
        JP_Login.setLayout(null);

        jLabel1.setText("Ingrese su nombre de usuario");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 20));
        JP_Login.add(jLabel1);
        jLabel1.setBounds(100, 90, 200, 20);

        Jtf_login.setName(""); // NOI18N
        Jtf_login.setPreferredSize(new java.awt.Dimension(100, 25));
        Jtf_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_loginActionPerformed(evt);
            }
        });
        Jtf_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Jtf_loginKeyPressed(evt);
            }
        });
        JP_Login.add(Jtf_login);
        Jtf_login.setBounds(150, 140, 102, 25);

        JBtn_Login.setText("Ingresar");
        JBtn_Login.setPreferredSize(new java.awt.Dimension(100, 25));
        JBtn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_LoginActionPerformed(evt);
            }
        });
        JP_Login.add(JBtn_Login);
        JBtn_Login.setBounds(150, 200, 100, 25);

        jDesktopPane1.add(JP_Login);
        JP_Login.setBounds(200, 100, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_loginActionPerformed

    private void JBtn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_LoginActionPerformed
        if(validateLogin()){
            myClient = new Client(SERVER_PORT, IP_SERVER_LOCAL, GET_USERS, null);
            myClient.start();
            
            String status = myClient.getStatus();
            while(status.equals("")){
                status = myClient.getStatus();
            }
            if(myClient.getStatus().equals(ACEPTADO)){
                String[] columnNames = {"Nombre de usuario"};
                String [] userList = myClient.getUserList();
                String [][] data = new String [userList.length][1];
                System.out.println(data[0].length);
                System.out.println(data.length);
                
                for (int i = 0; i < userList.length; i++) {
                    data[i][0] = userList[i];
                }
                
                DefaultTableModel model = new DefaultTableModel(data, columnNames);
                JTable_Users.setModel(model);
            }
            timer.start();
        }
    }//GEN-LAST:event_JBtn_LoginActionPerformed

    private boolean validateLogin(){
        if (!Jtf_login.getText().isEmpty()) {    
            userName = Jtf_login.getText();
            myClient = new Client(SERVER_PORT, IP_SERVER_LOCAL, VALIDATE_USER, userName);
            myClient.start();
            String status = myClient.getStatus();
            while(status.equals("")){
                status = myClient.getStatus();
            }
            if(myClient.getStatus().equals(ACEPTADO)){
                JP_Login.setVisible(false);
                JP_Start.setVisible(true);
                return true;
            }else{
                JOptionPane.showMessageDialog(null, "El nombre de usuario ya existe");
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de usuario");            
        }
        return false;
    }
    
    private void Jtf_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jtf_loginKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            if(validateLogin()){
                myClient = new Client(SERVER_PORT, IP_SERVER_LOCAL, GET_USERS, null);
                myClient.start();

                String status = myClient.getStatus();
                while(status.equals("")){
                    status = myClient.getStatus();
                }
                if(myClient.getStatus().equals(ACEPTADO)){
                    String[] columnNames = {"Nombre de usuario"};
                    String [] userList = myClient.getUserList();
                    String [][] data = new String [userList.length][1];
                    System.out.println(data[0].length);
                    System.out.println(data.length);

                    for (int i = 0; i < userList.length; i++) {
                        data[i][0] = userList[i];
                    }

                    DefaultTableModel model = new DefaultTableModel(data, columnNames);
                    JTable_Users.setModel(model);
                }
            }
        }
    }//GEN-LAST:event_Jtf_loginKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(JTable_IP.getSelectedRow() != -1){
            ipSelected = JTable_IP.getModel().getValueAt(JTable_IP.getSelectedRow(), JTable_IP.getSelectedColumn()).toString();                        
        }else{
            JOptionPane.showMessageDialog(null, "Servidor local seleccionado");
            ipSelected = IP_SERVER_LOCAL;
        }
        JP_Ipv4Available.setVisible(false);
        JP_Login.setVisible(true);
        
        myClient = new Client(SERVER_PORT, IP_SERVER_LOCAL);
        myClient.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBtn_inviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_inviteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_inviteActionPerformed

    private void JBtn_SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_SendMessageActionPerformed
        sendMessage();
    }//GEN-LAST:event_JBtn_SendMessageActionPerformed

    private void jTxtF_MessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtF_MessageKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            sendMessage();
        }
    }//GEN-LAST:event_jTxtF_MessageKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        crearFabrica("FuenteEnergia");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        crearFabrica("Mercado");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        crearFabrica("Mina");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        crearFabrica("Armeria");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        crearFabrica("Templo");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        crearConector();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void sendMessage(){
        myClient = new Client(SERVER_PORT, IP_SERVER_LOCAL, SEND_MESSAGE, userName + "-> " + jTxtF_Message.getText());
        myClient.start();
        
        String status = myClient.getStatus();
        while(status.equals("")){
            status = myClient.getStatus();
        }
        jTxtA_Conversation.setText(status);
        jTxtF_Message.setText("");
    }
    
    private void botones(){
        for (int i = 0; i<fila; i++){
            for (int j = 0; j<columna; j++){
                panelBotones[i][j] = new Boton(23 * i, 23 * j, 23, 23);
                jPanel1.add(panelBotones[i][j]);
            }
        }
    }
    
    public void crearFabrica(String tipo){
        
    }
    
    public void crearConector(){
        
    }
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_Login;
    private javax.swing.JButton JBtn_SendMessage;
    private javax.swing.JButton JBtn_invite;
    private javax.swing.JPanel JP_Ipv4Available;
    private javax.swing.JPanel JP_Login;
    private javax.swing.JPanel JP_Start;
    private javax.swing.JTable JTable_IP;
    private javax.swing.JTable JTable_Users;
    private javax.swing.JTextField Jtf_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTxtA_Conversation;
    private javax.swing.JTextField jTxtF_Message;
    // End of variables declaration//GEN-END:variables
}
